#FAST sheet "3 Initiative-E" headers have too many issues to import automatically -> define

#header list to apply to df
  init_headers <-c("fundingagency",
                   "mechanismname",
                   "primepartner",
                   "mechanismid",
                   "programarea",
                   "beneficiary",
                   "intervention_total_drop",
                   "notes_drop",
                   "initiative1",
                   "bilat_total_drop",
                   "bilat_appliedpipeline",
                   "bilat_new_gap",
                   "bilat_new_ghp_usaid",
                   "bilat_new_ghp_state",
                   "bilat_new_total_drop",
                   "bilat_circ.prev",
                   "bilat_hbhc.ct_se",
                   "bilat_hkid.se",
                   "bilat_hlab.asp",
                   "bilat_hmbl.asp",
                   "bilat_hmin.asp",
                   "bilat_htxd.ct",
                   "bilat_htxs.ct",
                   "bilat_hvab.prev",
                   "bilat_hvct.ct_hts",
                   "bilat_hvop.prev",
                   "bilat_hvsi.asp",
                   "bilat_hvtb.ct",
                   "bilat_idup.prev",
                   "bilat_mtct.ct_prev_hts",
                   "bilat_ohss.asp",
                   "bilat_pdcs.ct_se",
                   "bilat_pdtx.ct",
                   "bilat_val_drop",
                   "initiative2",
                   "init2_total_drop",
                   "init2_appliedpipeline",
                   "init2_new_gap",
                   "init2_new_ghp_usaid",
                   "init2_new_ghp_state",
                   "init2_new_total_drop",
                   "init2_circ.prev",
                   "init2_hbhc.ct_se",
                   "init2_hkid.se",
                   "init2_hlab.asp",
                   "init2_hmbl.asp",
                   "init2_hmin.asp",
                   "init2_htxd.ct",
                   "init2_htxs.ct",
                   "init2_hvab.prev",
                   "init2_hvct.ct_hts",
                   "init2_hvop.prev",
                   "init2_hvsi.asp",
                   "init2_hvtb.ct",
                   "init2_idup.prev",
                   "init2_mtct.ct_prev_hts",
                   "init2_ohss.asp",
                   "init2_pdcs.ct_se",
                   "init2_pdtx.ct",
                   "init2_val_drop",
                   "blank_drop",
                   "val_checkall_drop",
                   "val_bilat_drop",
                   "val_wcf_drop",
                   "val_faithbased_drop",
                   "val_sum_drop",
                   "val_origsum_drop",
                   "val_diff_drop")


#save
  save(init_headers, file = "data/init_headers.rda")

rm(init_headers)
